spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/research_system
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: false
    open-in-view: false

app:
  jwt:
    secret: ${JWT_SECRET:your-256-bit-secret-key-here-minimum-32-characters}
    expiration:
      ms: 3600000  # 1 hour
    refresh:
      expiration:
        ms: 2592000000  # 30 days 